### ISSUE TITLE
Possible redundant check

### ISSUE THREAD

**Issue by haslingerm** [WeaverDev/GDMEC#1]
I integrated your nice project into one of mine and the IDE threw up a warning about an always-true condition.
From my cursory investigation that's actually the case, so I wanted to let you know that there might be a bug in this guard clause:

https://github.com/WeaverDev/More-Effective-Godot-Coroutines/blob/4a31a7e18107246d59da3f53d1af8b5476bf7806/addons/GDMEC/Timing.cs#L1784-L1785

It can't be null and not null at the same time, so I suppose you meant to check something different here (maybe if `action` is not null).

**Comment by WeaverDev** [comment]
Thanks for the report, that is indeed a bug! It's been fixed on latest.
